name = "Tildagon badge simpulator"
description = "A simple simulator for Tildagon badges"
author = "Duncan Thomas <duncan.thomas@gmail.com"
packages = []

[files]
"./main.py" = "main.py"
"./async_queue.py" = "async_queue.py"
"./perf_timer.py" = "perf_timer.py"
"./app.py" = "app.py"
"./eeprom_i2c.py" = "eeprom_i2c.py"
"./eeprom_partition.py" = "eeprom_partition.py"
"./tildagonos.py" = "tildagonos.py"
"./leds.py" = "leds.py"
"./sys_colors.py" = "sys_colors.py"
"./sys_display.py" = "sys_display.py"
"./vfs.py" = "vfs.py"
"./settings.py" = "settings.py"

"./app_components/__init__.py" = "app_components/__init__.py"
"./app_components/layout.py" = "app_components/layout.py"
"./app_components/notification.py" = "app_components/notification.py"
"./app_components/utils.py" = "app_components/utils.py"
"./app_components/dialog.py" = "app_components/dialog.py"
"./app_components/menu.py" = "app_components/menu.py"
"./app_components/tokens.py" = "app_components/tokens.py"

"./system/__init__.py" = "system/__init__.py"

"./system/scheduler/__init__.py" = "system/scheduler/__init__.py"
"./system/scheduler/events.py" = "system/scheduler/events.py"

"./system/hexpansion/__init__.py" = "system/hexpansion/__init__.py"
"./system/hexpansion/app.py" = "system/hexpansion/app.py"
"./system/hexpansion/config.py" = "system/hexpansion/config.py"
"./system/hexpansion/events.py" = "system/hexpansion/events.py"
"./system/hexpansion/header.py" = "system/hexpansion/header.py"
"./system/hexpansion/util.py" = "system/hexpansion/util.py"

"./system/notification/__init__.py" = "system/notification/__init__.py"
"./system/notification/events.py" = "system/notification/events.py"

"./system/patterndisplay/__init__.py" = "system/patterndisplay/__init__.py"
"./system/patterndisplay/app.py" = "system/patterndisplay/app.py"
"./system/patterndisplay/events.py" = "system/patterndisplay/events.py"

"./system/eventbus.py" = "system/eventbus.py"

"./events/__init__.py" = "events/__init__.py"
"./events/input.py" = "events/input.py"

"./frontboards/__init__.py" = "frontboards/__init__.py"
"./frontboards/twentyfour.py" = "frontboards/twentyfour.py"

"./patterns/base.py" = "patterns/base.py"
"./patterns/cylon.py" = "patterns/cylon.py"
"./patterns/flash.py" = "patterns/flash.py"
"./patterns/off.py" = "patterns/off.py"
"./patterns/rainbow.py" = "patterns/rainbow.py"
