name: Build and Deploy
on: [push]
permissions:
  contents: write
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Checkout badge firmware
        uses: actions/checkout@v5
        with:
            repository: emfcamp/badge-2024-software
            path: badge-2024-software

      - name: Deploy 
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: .
